package doobie.labs.qb.pg
package cast

trait AssignmentCast[S <: String with Singleton, T <: String with Singleton]
  extends ExplicitCast[S, T]

object AssignmentCast extends AssignmentCastInstances {

  def apply[S <: String with Singleton, T <: String with Singleton](s: S, t: T): AssignmentCast[S, T] =
    new AssignmentCast[S, T] {
      val source = s
      val target = t
    }

}

trait AssignmentCastInstances extends ImplicitCastInstances {

  implicit val abstime_date          = AssignmentCast("abstime"      , "date"     )
  implicit val abstime_time          = AssignmentCast("abstime"      , "time"     )
  implicit val bool_bpchar           = AssignmentCast("bool"         , "bpchar"   )
  implicit val bool_citext           = AssignmentCast("bool"         , "citext"   )
  implicit val bool_text             = AssignmentCast("bool"         , "text"     )
  implicit val bool_varchar          = AssignmentCast("bool"         , "varchar"  )
  implicit val box_polygon           = AssignmentCast("box"          , "polygon"  )
  implicit val bpchar_char           = AssignmentCast("bpchar"       , "char"     )
  implicit val bpchar_citext         = AssignmentCast("bpchar"       , "citext"   )
  implicit val char_bpchar           = AssignmentCast("char"         , "bpchar"   )
  implicit val char_varchar          = AssignmentCast("char"         , "varchar"  )
  implicit val cidr_bpchar           = AssignmentCast("cidr"         , "bpchar"   )
  implicit val cidr_text             = AssignmentCast("cidr"         , "text"     )
  implicit val cidr_varchar          = AssignmentCast("cidr"         , "varchar"  )
  implicit val citext_bpchar         = AssignmentCast("citext"       , "bpchar"   )
  implicit val float4_int2           = AssignmentCast("float4"       , "int2"     )
  implicit val float4_int4           = AssignmentCast("float4"       , "int4"     )
  implicit val float4_int8           = AssignmentCast("float4"       , "int8"     )
  implicit val float4_numeric        = AssignmentCast("float4"       , "numeric"  )
  implicit val float8_float4         = AssignmentCast("float8"       , "float4"   )
  implicit val float8_int2           = AssignmentCast("float8"       , "int2"     )
  implicit val float8_int4           = AssignmentCast("float8"       , "int4"     )
  implicit val float8_int8           = AssignmentCast("float8"       , "int8"     )
  implicit val float8_numeric        = AssignmentCast("float8"       , "numeric"  )
  implicit val geometry_box          = AssignmentCast("geometry"     , "box"      )
  implicit val inet_bpchar           = AssignmentCast("inet"         , "bpchar"   )
  implicit val inet_cidr             = AssignmentCast("inet"         , "cidr"     )
  implicit val inet_citext           = AssignmentCast("inet"         , "citext"   )
  implicit val inet_text             = AssignmentCast("inet"         , "text"     )
  implicit val inet_varchar          = AssignmentCast("inet"         , "varchar"  )
  implicit val int4_int2             = AssignmentCast("int4"         , "int2"     )
  implicit val int4_money            = AssignmentCast("int4"         , "money"    )
  implicit val int8_int2             = AssignmentCast("int8"         , "int2"     )
  implicit val int8_int4             = AssignmentCast("int8"         , "int4"     )
  implicit val int8_money            = AssignmentCast("int8"         , "money"    )
  implicit val interval_reltime      = AssignmentCast("interval"     , "reltime"  )
  implicit val interval_time         = AssignmentCast("interval"     , "time"     )
  implicit val json_jsonb            = AssignmentCast("json"         , "jsonb"    )
  implicit val jsonb_json            = AssignmentCast("jsonb"        , "json"     )
  implicit val money_numeric         = AssignmentCast("money"        , "numeric"  )
  implicit val name_bpchar           = AssignmentCast("name"         , "bpchar"   )
  implicit val name_varchar          = AssignmentCast("name"         , "varchar"  )
  implicit val numeric_int2          = AssignmentCast("numeric"      , "int2"     )
  implicit val numeric_int4          = AssignmentCast("numeric"      , "int4"     )
  implicit val numeric_int8          = AssignmentCast("numeric"      , "int8"     )
  implicit val numeric_money         = AssignmentCast("numeric"      , "money"    )
  implicit val oid_int4              = AssignmentCast("oid"          , "int4"     )
  implicit val oid_int8              = AssignmentCast("oid"          , "int8"     )
  implicit val path_polygon          = AssignmentCast("path"         , "polygon"  )
  implicit val point_box             = AssignmentCast("point"        , "box"      )
  implicit val polygon_path          = AssignmentCast("polygon"      , "path"     )
  implicit val raster_box3d          = AssignmentCast("raster"       , "box3d"    )
  implicit val raster_bytea          = AssignmentCast("raster"       , "bytea"    )
  implicit val raster_geometry       = AssignmentCast("raster"       , "geometry" )
  implicit val regclass_int4         = AssignmentCast("regclass"     , "int4"     )
  implicit val regclass_int8         = AssignmentCast("regclass"     , "int8"     )
  implicit val regconfig_int4        = AssignmentCast("regconfig"    , "int4"     )
  implicit val regconfig_int8        = AssignmentCast("regconfig"    , "int8"     )
  implicit val regdictionary_int4    = AssignmentCast("regdictionary", "int4"     )
  implicit val regdictionary_int8    = AssignmentCast("regdictionary", "int8"     )
  implicit val regnamespace_int4     = AssignmentCast("regnamespace" , "int4"     )
  implicit val regnamespace_int8     = AssignmentCast("regnamespace" , "int8"     )
  implicit val regoper_int4          = AssignmentCast("regoper"      , "int4"     )
  implicit val regoper_int8          = AssignmentCast("regoper"      , "int8"     )
  implicit val regoperator_int4      = AssignmentCast("regoperator"  , "int4"     )
  implicit val regoperator_int8      = AssignmentCast("regoperator"  , "int8"     )
  implicit val regproc_int4          = AssignmentCast("regproc"      , "int4"     )
  implicit val regproc_int8          = AssignmentCast("regproc"      , "int8"     )
  implicit val regprocedure_int4     = AssignmentCast("regprocedure" , "int4"     )
  implicit val regprocedure_int8     = AssignmentCast("regprocedure" , "int8"     )
  implicit val regrole_int4          = AssignmentCast("regrole"      , "int4"     )
  implicit val regrole_int8          = AssignmentCast("regrole"      , "int8"     )
  implicit val regtype_int4          = AssignmentCast("regtype"      , "int4"     )
  implicit val regtype_int8          = AssignmentCast("regtype"      , "int8"     )
  implicit val text_char             = AssignmentCast("text"         , "char"     )
  implicit val text_citext           = AssignmentCast("text"         , "citext"   )
  implicit val timestamp_abstime     = AssignmentCast("timestamp"    , "abstime"  )
  implicit val timestamp_date        = AssignmentCast("timestamp"    , "date"     )
  implicit val timestamp_time        = AssignmentCast("timestamp"    , "time"     )
  implicit val timestamptz_abstime   = AssignmentCast("timestamptz"  , "abstime"  )
  implicit val timestamptz_date      = AssignmentCast("timestamptz"  , "date"     )
  implicit val timestamptz_time      = AssignmentCast("timestamptz"  , "time"     )
  implicit val timestamptz_timestamp = AssignmentCast("timestamptz"  , "timestamp")
  implicit val timestamptz_timetz    = AssignmentCast("timestamptz"  , "timetz"   )
  implicit val timetz_time           = AssignmentCast("timetz"       , "time"     )
  implicit val varchar_char          = AssignmentCast("varchar"      , "char"     )
  implicit val varchar_citext        = AssignmentCast("varchar"      , "citext"   )
  implicit val xml_bpchar            = AssignmentCast("xml"          , "bpchar"   )
  implicit val xml_text              = AssignmentCast("xml"          , "text"     )
  implicit val xml_varchar           = AssignmentCast("xml"          , "varchar"  )

}
