package doobie.labs.qb
package pg

import doobie.labs.qb.pg.cast.ExplicitCast
import shapeless._

/** Machinery to support Postgres ascriptions like <expr>::type. */
@SuppressWarnings(Array("org.wartremover.warts.Overloading"))
abstract class Ascription[S <: XString : ValueOf] {

  // Ascription for an expression: <expr>::type
  def ::[
    P <: HList,
    U <: HList,
    G <: HList,
    N <: HList,
    A <: XString
  ](e: PgExpr[P, U, G, N, A])(
    implicit ev: ExplicitCast[A, S]
  ): PgExpr[P, U, G, N, S] =
    ev(e)


  // Ascription for a literal: 42::int4
  // todo: explicit cast; i.e., 42::int2
  def ::[A](a: A)(
    implicit ev: Literal[A] { type Out = S }
  ): PgExpr[HNil, HNil, HNil, HNil, S] =
    PgExpr(a)

}

// All non-pg_ types in the defaut namespace.
object _abstime         extends Ascription["_abstime"]
object _aclitem         extends Ascription["_aclitem"]
object _bit             extends Ascription["_bit"]
object _bool            extends Ascription["_bool"]
object _box             extends Ascription["_box"]
object _bpchar          extends Ascription["_bpchar"]
object _bytea           extends Ascription["_bytea"]
object _char            extends Ascription["_char"]
object _cid             extends Ascription["_cid"]
object _cidr            extends Ascription["_cidr"]
object _circle          extends Ascription["_circle"]
object _cstring         extends Ascription["_cstring"]
object _date            extends Ascription["_date"]
object _daterange       extends Ascription["_daterange"]
object _float4          extends Ascription["_float4"]
object _float8          extends Ascription["_float8"]
object _gtsvector       extends Ascription["_gtsvector"]
object _inet            extends Ascription["_inet"]
object _int2            extends Ascription["_int2"]
object _int2vector      extends Ascription["_int2vector"]
object _int4            extends Ascription["_int4"]
object _int4range       extends Ascription["_int4range"]
object _int8            extends Ascription["_int8"]
object _int8range       extends Ascription["_int8range"]
object _interval        extends Ascription["_interval"]
object _json            extends Ascription["_json"]
object _jsonb           extends Ascription["_jsonb"]
object _line            extends Ascription["_line"]
object _lseg            extends Ascription["_lseg"]
object _macaddr         extends Ascription["_macaddr"]
object _money           extends Ascription["_money"]
object _name            extends Ascription["_name"]
object _numeric         extends Ascription["_numeric"]
object _numrange        extends Ascription["_numrange"]
object _oid             extends Ascription["_oid"]
object _oidvector       extends Ascription["_oidvector"]
object _path            extends Ascription["_path"]
object _pg_lsn          extends Ascription["_pg_lsn"]
object _point           extends Ascription["_point"]
object _polygon         extends Ascription["_polygon"]
object _record          extends Ascription["_record"]
object _refcursor       extends Ascription["_refcursor"]
object _regclass        extends Ascription["_regclass"]
object _regconfig       extends Ascription["_regconfig"]
object _regdictionary   extends Ascription["_regdictionary"]
object _regnamespace    extends Ascription["_regnamespace"]
object _regoper         extends Ascription["_regoper"]
object _regoperator     extends Ascription["_regoperator"]
object _regproc         extends Ascription["_regproc"]
object _regprocedure    extends Ascription["_regprocedure"]
object _regrole         extends Ascription["_regrole"]
object _regtype         extends Ascription["_regtype"]
object _reltime         extends Ascription["_reltime"]
object _text            extends Ascription["_text"]
object _tid             extends Ascription["_tid"]
object _time            extends Ascription["_time"]
object _timestamp       extends Ascription["_timestamp"]
object _timestamptz     extends Ascription["_timestamptz"]
object _timetz          extends Ascription["_timetz"]
object _tinterval       extends Ascription["_tinterval"]
object _tsquery         extends Ascription["_tsquery"]
object _tsrange         extends Ascription["_tsrange"]
object _tstzrange       extends Ascription["_tstzrange"]
object _tsvector        extends Ascription["_tsvector"]
object _txid_snapshot   extends Ascription["_txid_snapshot"]
object _uuid            extends Ascription["_uuid"]
object _varbit          extends Ascription["_varbit"]
object _varchar         extends Ascription["_varchar"]
object _xid             extends Ascription["_xid"]
object _xml             extends Ascription["_xml"]
object abstime          extends Ascription["abstime"]
object aclitem          extends Ascription["aclitem"]
object any              extends Ascription["any"]
object anyarray         extends Ascription["anyarray"]
object anyelement       extends Ascription["anyelement"]
object anyenum          extends Ascription["anyenum"]
object anynonarray      extends Ascription["anynonarray"]
object anyrange         extends Ascription["anyrange"]
object bit              extends Ascription["bit"]
object bool             extends Ascription["bool"]
object box              extends Ascription["box"]
object bpchar           extends Ascription["bpchar"]
object bytea            extends Ascription["bytea"]
object char             extends Ascription["char"]
object cid              extends Ascription["cid"]
object cidr             extends Ascription["cidr"]
object circle           extends Ascription["circle"]
object cstring          extends Ascription["cstring"]
object date             extends Ascription["date"]
object daterange        extends Ascription["daterange"]
object event_trigger    extends Ascription["event_trigger"]
object fdw_handler      extends Ascription["fdw_handler"]
object float4           extends Ascription["float4"]
object float8           extends Ascription["float8"]
object gtsvector        extends Ascription["gtsvector"]
object inet             extends Ascription["inet"]
object int2             extends Ascription["int2"]
object int2vector       extends Ascription["int2vector"]
object int4             extends Ascription["int4"]
object int4range        extends Ascription["int4range"]
object int8             extends Ascription["int8"]
object int8range        extends Ascription["int8range"]
object internal         extends Ascription["internal"]
object interval         extends Ascription["interval"]
object json             extends Ascription["json"]
object jsonb            extends Ascription["jsonb"]
object language_handler extends Ascription["language_handler"]
object line             extends Ascription["line"]
object lseg             extends Ascription["lseg"]
object macaddr          extends Ascription["macaddr"]
object money            extends Ascription["money"]
object name             extends Ascription["name"]
object numeric          extends Ascription["numeric"]
object numrange         extends Ascription["numrange"]
object oid              extends Ascription["oid"]
object oidvector        extends Ascription["oidvector"]
object opaque           extends Ascription["opaque"]
object path             extends Ascription["path"]
object point            extends Ascription["point"]
object polygon          extends Ascription["polygon"]
object record           extends Ascription["record"]
object refcursor        extends Ascription["refcursor"]
object regclass         extends Ascription["regclass"]
object regconfig        extends Ascription["regconfig"]
object regdictionary    extends Ascription["regdictionary"]
object regnamespace     extends Ascription["regnamespace"]
object regoper          extends Ascription["regoper"]
object regoperator      extends Ascription["regoperator"]
object regproc          extends Ascription["regproc"]
object regprocedure     extends Ascription["regprocedure"]
object regrole          extends Ascription["regrole"]
object regtype          extends Ascription["regtype"]
object reltime          extends Ascription["reltime"]
object smgr             extends Ascription["smgr"]
object text             extends Ascription["text"]
object tid              extends Ascription["tid"]
object time             extends Ascription["time"]
object timestamp        extends Ascription["timestamp"]
object timestamptz      extends Ascription["timestamptz"]
object timetz           extends Ascription["timetz"]
object tinterval        extends Ascription["tinterval"]
object trigger          extends Ascription["trigger"]
object tsm_handler      extends Ascription["tsm_handler"]
object tsquery          extends Ascription["tsquery"]
object tsrange          extends Ascription["tsrange"]
object tstzrange        extends Ascription["tstzrange"]
object tsvector         extends Ascription["tsvector"]
object txid_snapshot    extends Ascription["txid_snapshot"]
object unknown          extends Ascription["unknown"]
object uuid             extends Ascription["uuid"]
object varbit           extends Ascription["varbit"]
object varchar          extends Ascription["varchar"]
// object void             extends Ascription["void"]
object xid              extends Ascription["xid"]
object xml              extends Ascription["xml"]
